### ISSUE TITLE
open Hyper in the working directory

### ISSUE THREAD

**Issue by mittalyashu** [hharnisc/hypercwd#38]
How to open hyper in the working directory? (Not working even after installing)

![image](https://user-images.githubusercontent.com/29014463/35671547-c16e3282-0761-11e8-97a9-c1fcc5da129f.png)

**Comment by hharnisc** [comment]
Hello @mittalyashu :wave: 

From the screenshot it looks like you're trying to open Hyper from the Context menu at the directory. Depending on where that folder is there might still be some bugs around that: https://github.com/zeit/hyper/issues/1305

`hypercwd` will set the current working directory (or the initial directory) after Hyper has been opened, so I think what you're experiencing is a bug in Hyper rather than CWD.

**Comment by mittalyashu** [comment]
I have installed the `hypercwd`, but it is not opening the initial directory.
